export const ORDER_LIST = "ORDER_LIST";
export const ORDER_ERROR = "ORDER_ERROR";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const INDIVIDUAL_ORDER_UPD_NAME = "INDIVIDUAL_ORDER_UPD_NAME";
export const INDIVIDUAL_ORDER_UPD_LASTNAME = "INDIVIDUAL_ORDER_UPD_LASTNAME";
export const INDIVIDUAL_ORDER_UPD_PHONE = "INDIVIDUAL_ORDER_UPD_PHONE";
export const INDIVIDUAL_ORDER_UPD_EMAIL = "INDIVIDUAL_ORDER_UPD_EMAIL";
export const INDIVIDUAL_ORDER_UPD_ADDRESS = "INDIVIDUAL_ORDER_UPD_ADDRESS";
export const INDIVIDUAL_ORDER_UPD_CITY = "INDIVIDUAL_ORDER_UPD_CITY";
export const INDIVIDUAL_ORDER_UPD_COUNTRY = "INDIVIDUAL_ORDER_UPD_COUNTRY";
export const INDIVIDUAL_ORDER_UPD_POSTCODE = "INDIVIDUAL_ORDER_UPD_POSTCODE";
export const INDIVIDUAL_ORDER_UPD_NOTES = "INDIVIDUAL_ORDER_UPD_NOTES";
export const INDIVIDUAL_ORDER_UPD_PRICE = "INDIVIDUAL_ORDER_UPD_PRICE";
export const INDIVIDUAL_ORDER_UPD_ORDERITEMS =
  "INDIVIDUAL_ORDER_UPD_ORDERITEMS";
export const INDIVIDUAL_ORDER_CLEAN = "INDIVIDUAL_ORDER_CLEAN";
export const INDIVIDUAL_ORDER_ERROR = "INDIVIDUAL_ORDER_ERROR";
export const INDIVIDUAL_ORDER_LIST = "INDIVIDUAL_ORDER_LIST";
