export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_UPDATE_FAILURE = "PRODUCT_UPDATE_FAILURE";
export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_DELETE_FAILURE = "PRODUCT_DELETE_FAILURE";
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_ADD_FAILURE = "PRODUCT_ADD_FAILURE";
export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const INDIVIDUAL_PRODUCT_LIST = "INDIVIDUAL_PRODUCT_LIST";
export const INDIVIDUAL_PRODUCT_ERROR = "INDIVIDUAL_PRODUCT_ERROR";
export const INDIVIDUAL_PRODUCT_CLEAN = "INDIVIDUAL_PRODUCT_CLEAN";
export const INDIVIDUAL_PRODUCT_UPD_NAME = "INDIVIDUAL_PRODUCT_UPD_NAME";
export const INDIVIDUAL_PRODUCT_UPD_DESCRIPTION =
  "INDIVIDUAL_PRODUCT_UPD_DESCRIPTION";
export const INDIVIDUAL_PRODUCT_UPD_PRICE = "INDIVIDUAL_PRODUCT_UPD_PRICE";
export const INDIVIDUAL_PRODUCT_UPD_IMAGES = "INDIVIDUAL_PRODUCT_UPD_IMAGES";
export const INDIVIDUAL_PRODUCT_UPD_CATEGORY =
  "INDIVIDUAL_PRODUCT_UPD_CATEGORY";
export const INDIVIDUAL_PRODUCT_UPD_PUBLIC_IMAGE =
  "INDIVIDUAL_PRODUCT_UPD_PUBLIC_IMAGE";
export const INDIVIDUAL_PRODUCT_UPD_INSTOCK = "INDIVIDUAL_PRODUCT_UPD_INSTOCK";
export const INDIVIDUAL_PRODUCT_UPD_OVERVIEW =
  "INDIVIDUAL_PRODUCT_UPD_OVERVIEW";
